services:
  postgres:
    image: postgres:17-alpine
    shm_size: 1gb
    environment:
      POSTGRES_DB: msgscan
      POSTGRES_USEDR: postgres
      POSTGRES_PASSWORD: let-me-in
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-7454}:5432"
