const MESSAGE_STATUS = {
  PENDING: 0,
  SUCCESS: 1,
  FAILED: 2,
}

const PONDER_PUBLISH_SCHEMA = 'publish'
const MESSAGE_TABLE = 'Message'

export { MESSAGE_STATUS, MESSAGE_TABLE, PONDER_PUBLISH_SCHEMA }
