name: Deploy develop

on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy to Vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          script_run: false
          dist_path: packages/web
          project_name: msgscan
          enable_cache: true
          enable_notify_comment: true
          enable_notify_slack: true
          slack_channel: public-msgport
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

